config/routes.rb
Rails.application.routes.draw do
  get 'site_memos/index/:site_id', to: 'site_memos#index', as: :site_memos_index
  post 'site_memos/update_bulk_order/:site_id/:order', to: 'site_memos#update_bulk_order', as: :site_memos_update_bulk_order
  get 'site_memos/show_switcher/:kind/:child_id', to: 'site_memos#show_switcher', as: :site_memos_show_switcher
  get 'site_memos/new_step1/:site_id', to: 'site_memos#new_step1', as: :site_memos_new_step1
  post 'site_memos/form_switcher'
  delete 'site_memos/destroy/:kind/:child_id', to: 'site_memos#destroy', as: :site_memos_destroy
  get 'inner_sashes/new_step2'
  post 'inner_sashes/new_append_room'
  get 'inner_sashes/new_step3'
  patch 'inner_sashes/new_append_basic_info'
  get 'inner_sashes/new_step4'
  patch 'inner_sashes/new_append_shoji_and_glass'
  get 'inner_sashes/new_step5'
  patch 'inner_sashes/new_append_photo_and_others'
  get 'inner_sashes/new_comfirmation'
  get 'inner_sashes/show/:id', to: 'inner_sashes#show', as: :inner_sashes_show
  delete 'inner_sashes/destroy/:id', to: 'inner_sashes#destroy', as: :inner_sashes_destroy
  post 'inner_sashes/navigate_page/:id/:template', to:'inner_sashes#navigate_page', as: :inner_sashes_navigate_page
  get 'inner_sashes/edit_room/:id', to: 'inner_sashes#edit_room', as: :inner_sashes_edit_room
  post 'inner_sashes/update_order/:id/:order', to: 'inner_sashes#update_order', as: :inner_sashes_update_order
  get 'inner_sashes/switch/:template/:id', to: 'inner_sashes#switch', as: :inner_sashes_switch
  patch 'inner_sashes/update/:id', to: 'inner_sashes#update', as: :inner_sashes_update
  patch 'inner_sashes/glass_append'
  delete 'photos/destroy_existing_photo_form/:id', to: 'photos#destroy_existing_photo_form', as: :photos_destroy_existing_photo_form
  delete 'photos/destroy_new_photo_form/:index', to: 'photos#destroy_new_photo_form', as: :photos_destroy_new_photo_form
  root 'homes#top'
  get 'sign_in/index'
  get 'sign_up/index'
  get 'sign_up/step1'
  get 'sign_up/step2'
  get 'sign_up/done'
  get 'sign_up/resend_confirmation_code'
  post 'sign_up/create'
  get 'sites/index'
  get 'sites/new'
  delete 'sites/destroy/:id', to: 'sites#destroy', as: :sites_destroy
  get 'sites/search_contractor'
  post 'sites/create'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/sign_up_controller.rb
class SignUpController < ApplicationController
  before_action :validates_step1, only: :step2

  def index
    
  end
  
  def step1
    
  end
  
  def step2(email:, name:)
    #認証コードをメールアドレスに送信
    create_and_send_confirmation_code(email: email, name: name)
  end

  def create(confirmation_code:)
    user = User.new(
      name: session[:name],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation]
    )
    if check_confirmation_code?(confirmation_code: confirmation_code) && user.save!
      sign_in(:user, user)
      redirect_to sign_up_done_path, notice: 'アカウントの作成が完了しました'
    else
      redirect_to sign_up_step2_path, alert: '認証コードが間違っています'
    end
  end

  def done

  end

  def resend_confirmation_code
    create_and_send_confirmation_code(email: session[:email], name: session[:name])
    render :step2, notice: '確認コードを再送しました'
  end


  private

  def validates_step1(name:, email: ,password:, password_confirmation:)
    session[:name] = name
    session[:email] = email
    session[:password] = password
    session[:password_confirmation] = password_confirmation

    user = User.new(
      name: session[:name],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation]
    )
    
    redirect_to sign_up_step1_path, notice: user.errors.full_messages unless user.valid?
  end

  def create_and_send_confirmation_code(email:, name:)
    context = OneTimeAuthentication.find_context(:sign_up)
    one_time_authentication = OneTimeAuthentication.create_one_time_authentication(
      context,
      email
    )
    ConfirmMailer.send_when_sign_up_step1(email: email, name: name, confirmation_code: one_time_authentication.password).deliver
    session[:client_token] = one_time_authentication.client_token
  end

  def check_confirmation_code?(confirmation_code:)
    context = OneTimeAuthentication.find_context(:sign_up)
    one_time_authentication = OneTimeAuthentication.find_one_time_authentication(
      context,
      session[:email]
    )
    new_client_token = one_time_authentication.authenticate_one_time_client_token!(session[:client_token])
    one_time_password = one_time_authentication.authenticate_one_time_password!(confirmation_code)
    valid_faile_count = one_time_authentication.under_valid_failed_count?
    if new_client_token && one_time_password && valid_faile_count
      return true
    else
      return false
    end
  end
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/views/sign_up/done.html.erb
<div class="container">
  <div class="row justify-content-center text-center" style="margin-top: 28vh;">
    <h5>新規登録が完了しました。</h5>
    <p class='mt-5'>完了ボタンを押し<br>一覧画面に遷移してください</p>
    <div class="row justify-content-center p-3 submit-btn mb-lg-5">
      <%= link_to '完了' , sites_index_path, class:'btn btn-primary col-9 col-md-4 col-lg-2' %>
    </div>
  </div>
</div>

app/views/sign_up/index.html.erb
<div class="container-fluid bg-image">
  <div class="container">
    <div class="row justify-content-center">
      <%= image_tag 'logo.png', class: 'logo col-md-8 col-lg-5' %>
    </div>
    <div class="buttons mt-5">
      <div class="row justify-content-center p-3">
        <%= link_to 'メールアドレスで登録', sign_up_step1_path, class: 'btn btn-light btn-light-custom col-10 col-md-5 col-lg-3' %>
      </div>
      <div class="row justify-content-center p-3">
        <%= link_to(user_line_omniauth_authorize_path, class: 'row col-10 col-md-5 col-lg-3 text-center line-btn bright-color', method: :post) do %>
          <span class="col align-self-center line-text">LINEで登録</span>
        <% end %>
      </div>
      <div class="row justify-content-center p-3">
        <%= link_to(user_google_oauth2_omniauth_authorize_path, class: 'row col-10 col-md-5 col-lg-3 text-center google-btn', method: :post) do %>
          <span class="col align-self-center google-text">Googleで登録</span>
        <% end %>
      </div>
    </div>
    <div class="text row justify-content-center mt-3 mt-md-5">
      <div class="col col-lg-3 border-bottom mb-3 bright-color"></div>
      <p class='col-8 col-sm-6 col-md-5 col-lg-3 p-0 text-center mb-1 fw-bold bright-color'>アカウントをお持ちでない方</p>
      <div class="col col-lg-3 border-bottom mb-3 bright-color"></div>
    </div>
    <div class="row justify-content-center text-center p-3">
      <%= link_to 'ログイン', sign_in_index_path, class: 'btn btn-primary col-10 col-md-5 col-lg-3' %>
    </div>
  </div>
</div>

app/views/sign_up/step1.html.erb
<div class="bar mt-5">
  <!--ここに進捗バーが表示 -->
</div>
<div class="container" style="margin-top: 15vh;">
  <%= form_with url: sign_up_step2_path, method: :get ,local: true, class: 'row justify-content-center' do |f| %>
    <div class="col-11 col-md-8 col-lg-5 mb-3 mb-md-4">
      <%= f.label :name, '名前', class: 'form-label' %><span class="badge bg-danger ms-2">必須</span><br />
      <%= f.text_field :name, class: 'form-control', autocomplete: 'name', maxlength:'15', required: true %>
    </div>
    <div class="d-none d-lg-block col-lg-12"></div>
    <div class="col-11 col-md-8 col-lg-5 mb-3 mb-md-4">
      <%= f.label :email, 'メールアドレス', class: 'form-label' %><span class="badge bg-danger ms-2">必須</span><br />
      <%= f.email_field :email, class: 'form-control', autocomplete: 'email', required: true %>
    </div>
    <!--jsでパスワードが一致していないとき、警告を入れる予定-->
    <div class="d-none d-lg-block col-lg-12"></div>
    <div class="col-11 col-md-8 col-lg-5 mb-3 mb-md-4">
      <%= f.label :password, 'パスワード', class: 'form-label' %><span class="badge bg-danger ms-2">必須</span><br />
      <%= f.password_field :password, class: 'form-control', autocomplete: 'new-password', required: true %>
    </div>
    <div class="d-none d-lg-block col-lg-12"></div>
    <div class="col-11 col-md-8 col-lg-5 mb-3 mb-md-4">
      <%= f.label :password_confirmation, 'パスワード(確認用)', class: 'form-label' %><span class="badge bg-danger ms-2">必須</span><br />
      <%= f.password_field :password_confirmation, class: 'form-control', autocomplete: 'new-password', required: true %>
    </div>
    <div class="row justify-content-center p-3 submit-btn mb-lg-5">
      <%= f.submit '次へ', class: 'btn btn-primary col-9 col-md-4 col-lg-2' %>
    </div>
  <% end %>
</div>

app/views/sign_up/step2.html.erb
<div class="bar mt-5">
  <!--ここに進捗バーが表示 -->
</div>
<div class="container" style="margin-top: 28vh;">
  <%= form_with url: sign_up_create_path, local: true, class: 'row justify-content-center' do |f| %>
    <div class="col-11 col-md-8 col-lg-5 mb-3 mb-md-4">
      <%= f.label :confirmation_code, '認証コード', class: 'form-label' %><span class="badge bg-danger ms-2">必須</span><br />
      <%= f.number_field :confirmation_code,class: 'form-control', autocomplete: 'confirmation_code', required: true %>
    </div>
    <div class="row justify-content-center p-3">
      <%= f.submit '認証', class: 'btn btn-primary col-9 col-md-4 col-lg-2' %>
    </div>
  <% end %>
  <div style='margin-top: 10vh;'>
    <div class="text-center">
      <h5>メールが届かない場合</h5>
      <%= link_to 'こちら', 'javascript:void(0)', class: 'text-primary border-bottom border-primary' ,'data-bs-toggle':"collapse", role: "button", href: "#collapseList", "aria-expanded":"false", "aria-controls":"collapseList" %>をご確認ください
    </div>
    <div class="collapse row justify-content-center mt-3" id='collapseList'>
      <ul class="list-group list-group-numbered mb-3 col-11 col-md-8 col-lg-5">
        <li class='list-group-item'>迷惑メールフォルダの確認</li>
        <li class='list-group-item'>メールアドレスの再確認</li>
        <li class='list-group-item'>メールフィルタの設定</li>
        <li class='list-group-item'>通信環境の確認</li>
        <li class='list-group-item'>再送信の試行<br>「再送するボタン」を押してください</li>
      </ul>
      <div class="row justify-content-center p-3 mb-3">
        <!-- 3分に一回押せるようにする -->
        <%= link_to '再送する', sign_up_resend_confirmation_code_path, class: 'btn btn-primary col-9 col-md-4 col-lg-2 '%>
      </div>
    </div>
  </div>

</div>