config/routes.rb
Rails.application.routes.draw do
  get 'site_memos/index/:site_id', to: 'site_memos#index', as: :site_memos_index
  post 'site_memos/update_bulk_order/:site_id/:order', to: 'site_memos#update_bulk_order', as: :site_memos_update_bulk_order
  get 'site_memos/show_switcher/:kind/:child_id', to: 'site_memos#show_switcher', as: :site_memos_show_switcher
  get 'site_memos/new_step1/:site_id', to: 'site_memos#new_step1', as: :site_memos_new_step1
  post 'site_memos/form_switcher'
  delete 'site_memos/destroy/:kind/:child_id', to: 'site_memos#destroy', as: :site_memos_destroy
  get 'inner_sashes/new_step2'
  post 'inner_sashes/new_append_room'
  get 'inner_sashes/new_step3'
  patch 'inner_sashes/new_append_basic_info'
  get 'inner_sashes/new_step4'
  patch 'inner_sashes/new_append_shoji_and_glass'
  get 'inner_sashes/new_step5'
  patch 'inner_sashes/new_append_photo_and_others'
  get 'inner_sashes/new_comfirmation'
  get 'inner_sashes/show/:id', to: 'inner_sashes#show', as: :inner_sashes_show
  delete 'inner_sashes/destroy/:id', to: 'inner_sashes#destroy', as: :inner_sashes_destroy
  post 'inner_sashes/navigate_page/:id/:template', to:'inner_sashes#navigate_page', as: :inner_sashes_navigate_page
  get 'inner_sashes/edit_room/:id', to: 'inner_sashes#edit_room', as: :inner_sashes_edit_room
  post 'inner_sashes/update_order/:id/:order', to: 'inner_sashes#update_order', as: :inner_sashes_update_order
  get 'inner_sashes/switch/:template/:id', to: 'inner_sashes#switch', as: :inner_sashes_switch
  patch 'inner_sashes/update/:id', to: 'inner_sashes#update', as: :inner_sashes_update
  patch 'inner_sashes/glass_append'
  delete 'photos/destroy_existing_photo_form/:id', to: 'photos#destroy_existing_photo_form', as: :photos_destroy_existing_photo_form
  delete 'photos/destroy_new_photo_form/:index', to: 'photos#destroy_new_photo_form', as: :photos_destroy_new_photo_form
  root 'homes#top'
  get 'sign_in/index'
  get 'sign_up/index'
  get 'sign_up/step1'
  get 'sign_up/step2'
  get 'sign_up/done'
  get 'sign_up/resend_confirmation_code'
  post 'sign_up/create'
  get 'sites/index'
  get 'sites/new'
  delete 'sites/destroy/:id', to: 'sites#destroy', as: :sites_destroy
  get 'sites/search_contractor'
  post 'sites/create'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/inner_sash.rb
class InnerSash < ApplicationRecord
  attr_accessor :template

  belongs_to :site_memo
  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true

  enum color: { c_undecided: 0, white: 1}
  enum sash_type: { t_undecided: 0, sliding: 1, opening: 2}
  enum hanging_origin: { h_undecided: 0, right: 1, left: 2}
  enum glass_color: { gc_undecided: 0, green: 1, clear: 2}
  enum glass_thickness: { gt_undecided: 0, single: 1, double: 2}
  enum glass_kind: { gk_undecided: 0, transparent: 1, hazy: 2}
  enum order: { unordered: 0 , ordered: 1 }

  validates :room, presence: true, length: { maximum:15 }
  validates :width_up_size, presence: true, size: true
  validates :width_down_size, presence: true, size: true
  validates :width_middle_size, presence: true, size: true
  validates :height_left_size, presence: true, size: true
  validates :height_middle_size, presence: true, size: true
  validates :height_right_size, presence: true, size: true
  validates :width_frame_depth, presence: true, size: true
  validates :height_frame_depth, presence: true ,size: true
  validates :color, presence: true
  validates :is_flat_bar, inclusion: {in: [true, false]}
  validates :key_height, presence: true
  validates :sash_type, presence: true
  validates :number_of_shoji, presence: true
  validates :middle_frame_height, presence: true
  validates :is_adjust, inclusion: {in: [true, false]}
  validates :hanging_origin, presence: true 
  validates :glass_color, presence: true
  validates :glass_kind, presence: true
  validates :glass_thickness, presence: true
  validates :is_low_e, inclusion: {in: [true, false]}

  def previous
    InnerSash.eager_load(site_memo: :site).where(site: {id: self.site_memo.site_id}).where("inner_sashes.id<?", self.id).order(id: :desc).first
  end

  def next
    InnerSash.eager_load(site_memo: :site).where(site: {id: self.site_memo.site_id}).where("inner_sashes.id>?", self.id).order(id: :asc).first
  end

  def destroy_last_with(site_memo:)
    self.transaction do
      self.destroy
      site_memo.destroy if site_memo.inner_sashes.size == Settings.child[:none]
    end
  end
end

app/controllers/inner_sashes_controller.rb
class InnerSashesController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_inner_sash, only: [:show, :switch, :navigate_page, :update_order, :edit_room, :update]
  before_action :set_site_memo, only: [:new_step2, :new_step3, :new_step4, :new_step5,
                                       :new_append_room, :new_append_shoji_and_glass, 
                                       :new_append_photo_and_others, :new_append_basic_info, :new_comfirmation]
  before_action :load_inner_sashes, only: [:new_step2, :new_append_room, :new_step3, :new_append_basic_info, :new_step4,
                                          :new_append_shoji_and_glass, :new_step5, :new_append_photo_and_others,
                                          :new_comfirmation]

  def new_step2
    # fields_forを使わないのはinner_sashのフォームは一つにしたいため
    @inner_sash = InnerSash.new
    @site_memo.update_status(action: action_name)
  end

  def new_append_room
    @inner_sash = InnerSash.new(inner_sash_params.merge(site_memo_id: @site_memo.id))
    @inner_sash = InnerSash.new if @inner_sash.save
    # 保存失敗したら、パラメーターを元に作ったインスタンス返す
  end

  def new_step3
    @site_memo.update_status(action: action_name)
  end

  def new_append_basic_info
    return redirect_to inner_sashes_new_step4_path if @site_memo.update(site_memo_params)
    return render "new_step3", status: :unprocessable_entity
  end

  def new_step4
    @site_memo.update_status(action: action_name)
  end

  def new_append_shoji_and_glass
    return redirect_to inner_sashes_new_step5_path if @site_memo.update(site_memo_params)
    return render "new_step4", status: :unprocessable_entity
  end

  def new_step5
    @site_memo.update_status(action: action_name)
  end

  def new_append_photo_and_others
    return redirect_to inner_sashes_new_comfirmation_path if @site_memo.update(site_memo_params)
    return render 'new_step5', status: :unprocessable_entity
  end

  def new_comfirmation
    @site_memo.update_status(action: action_name)
  end
  
  def show(id:)
    @inner_sash = InnerSash.preload(site_memo: :site).find(id)
    @order_key = get_opposite_order_key(inner_sash: @inner_sash)
    @template = 'basic_info'
    @draw_temp = 'opening_drawing'
  end

  def update_order(id:, order:)
    @inner_sash.update!(order: order)
    @order_key = get_opposite_order_key(inner_sash: @inner_sash)
    flash.now.notice = "#{InnerSash.orders_i18n[order.to_sym]}にしました"
  end

  def destroy(id:)
    inner_sash = InnerSash.find(id)
    inner_sash.destroy_last_with(site_memo: inner_sash.site_memo)
    redirect_to site_memos_index_path(site_id: inner_sash.site_memo.site_id), notice: "メモを削除しました"
  end

  def navigate_page(id:, template:)
    @inner_sash = InnerSash.preload(site_memo: :site).find(id.to_i)
    @order_key = get_opposite_order_key(inner_sash: @inner_sash)
    @template = template
    @draw_temp = 'opening_drawing'
  end

  def switch(template:, id:)
     # templateはbasic_info、shoji_and_glass、photo_and_others
     # h_cross_drawing w_cross_drawing edit_roomのどれか
    # render "#{template}", content_type: 'text/vnd.turbo-stream.html'
    @draw_temp = template
    @template = template
    render "#{template}"
  end

  def edit_room(id:)

  end

  def update(id:)
    @inner_sash.update!(inner_sash_params)

    # templateはbasic_info、shoji_and_glass、photo_and_othersのどれか
    @template = inner_sash_params[:template]
    flash.now.notice = I18n.t("inner_sashes.update.#{@template}") + "を更新しました"
    render "#{@template}", content_type: 'text/vnd.turbo-stream.html'
  end

private

  def inner_sash_params
    params.require(:inner_sash).permit(:room, :number_of_shoji, :width_up_size, :width_down_size, :width_middle_size, 
                                      :height_left_size, :height_middle_size, :height_right_size, :width_frame_depth, :height_frame_depth,
                                      :sash_type, :color, :number_of_shoji, :hanging_origin, :is_flat_bar, :is_adjust, 
                                      :glass_thickness, :glass_kind, :glass_color, :is_low_e, :key_height, :middle_frame_height,
                                      :template, photos_attributes: [:id, :file_name, :_destroy])
  end

  def site_memo_params
    params.require(:site_memo).permit(:remark, inner_sashes_attributes: [:id, :room, :number_of_shoji, :width_up_size, :width_down_size, :width_middle_size, 
                                      :height_left_size, :height_middle_size, :height_right_size, :width_frame_depth, :height_frame_depth,
                                      :color, :is_flat_bar, :hanging_origin, :key_height, :sash_type, :middle_frame_height, :is_adjust,
                                      :glass_color, :glass_thickness, :glass_kind, :is_low_e, photos_attributes: [:id, :file_name, :_destroy]])
  end

  def load_inner_sashes
    @inner_sashes = InnerSash.eager_load(:site_memo, :photos).where(site_memo: {kind: 'inner_sash', site_id: session[:site_id]})
  end

  def set_site_memo
    @site_memo = SiteMemo.find_by(kind: 'inner_sash', site_id: session[:site_id])
  end

  def correct_inner_sash(id:)
    @inner_sash = InnerSash.find(id)
    redirect_to root_path if @inner_sash.site_memo.site.user_id != current_user.id
  end
end

app/controllers/inner_sashs_controller.rb
class InnerSashsController < ApplicationController
  def new_step2(site_id:)
    #下書きがあれば下書きからデータを取ってくる処理を追加
    @site_id = site_id
  end

  def new_step3
   
  end

  def room_append(room:, width_up_size:, width_middle_size:, width_down_size:,
                  height_left_size:, height_right_size:, height_middle_size:,
                  height_frame_depth:, width_frame_depth:, site_id:)
    #インスタンスを作成
    site_memo = SiteMemo.new(kind: :inner_sash, site_id: site_id)
    inner_sash = site_memo.inner_sashes.build(room: room, width_up_size: width_up_size, width_middle_size: width_middle_size, width_down_size: width_down_size,
                                height_left_size: height_left_size, height_middle_size: height_middle_size, height_right_size: height_right_size,
                                height_frame_depth: height_frame_depth, width_frame_depth: width_frame_depth)
    return redirect_to inner_sashs_new_step2_path, notice: inner_sash.errors.full_messages unless inner_sash.save!
    @inner_sash = inner_sash.attributes
  end
end

app/helpers/inner_sashes_helper.rb
module InnerSashesHelper
  def calc_order_size(*size)
    return size.min
  end

  def boolean_to_int(boolean)
    return 1 if boolean
    return 0
  end

  def is_active(template, compare_temp)
    return 'active' if template == compare_temp 
  end
end

app/views/inner_sashes/_accessorie_fields.html.erb
<div class='row justify-content-center position-relative mt-3'>
  <div class='col-11 row border-index p-1 mb-3' style='height:40px;'>
    <span class='col-5'>
      <%= inner_sash.label :is_flat_bar, '平板', class: 'form-label' %>
    </span>
    <span class='col-7'>
      <%= inner_sash.select :is_flat_bar ,[['有',1],['無',0]], {selected: boolean_to_int(inner_sash.object.is_flat_bar)}, class: 'form-select basic-form' %>
    </span>
  </div>
  <div class='col-11 row border-index p-1 mb-3' style='height:60px;'>
    <span class='col-5'>
      <%= inner_sash.label :is_adjust, class: 'form-label' do %>
        アジャスト<br>上枠
      <% end %>
    </span>
    <span class='col-7'>
      <%= inner_sash.select :is_adjust ,[['有',1],['無',0]], {selected: boolean_to_int(inner_sash.object.is_adjust)}, class: 'form-select basic-form' %>
    </span>
  </div>
  <div class="col-11 row justify-content-center">
    <div class="col-10 btn btn-primary p-0">
      <%= link_to_add_association inner_sash, :photos,
        data: { association_insertion_node: "#add-point-#{inner_sash.object.id}",association_insertion_method: 'after'} do %>
        <p class='bright-color m-0'><i class="bi bi-plus h4 align-middle"></i><span class='d-inline-block align-middle'>写真追加</span></p>
      <% end %>
    </div>
    <%= inner_sash.fields_for :photos do |photo| %>
      <%= render 'photo_fields', f: photo %>
    <% end %>
    <div id="add-point-<%= inner_sash.object.id %>"></div>
  </div>
</div>

app/views/inner_sashes/_form_size.html.erb
<div class="form-group">
  <%= inner_sash.label :width_up_size, '上：' %>
  <%= inner_sash.number_field :width_up_size, required: true, min: 1 %>
</div>
<div class="form-group">
  <%= inner_sash.label :width_middle_size, '中：' %>
  <%= inner_sash.number_field :width_middle_size, required: true, min: 1 %>
</div>
<div class="form-group">
  <%= inner_sash.label :width_down_size, '下：' %>
  <%= inner_sash.number_field :width_down_size, required: true, min: 1 %>
</div>
<div class="form-group">
  <%= inner_sash.label :height_left_size, '左：' %>
  <%= inner_sash.number_field :height_left_size, required: true, min: 1 %>
</div>
<div class="form-group">
  <%= inner_sash.label :height_middle_size, '中：' %>
  <%= inner_sash.number_field :height_middle_size, required: true, min: 1 %>
</div>
<div class="form-group">
  <%= inner_sash.label :height_right_size, '右：' %>
  <%= inner_sash.number_field :height_right_size, required: true, min: 1 %>
</div>
<div class="form-group">
  <%= inner_sash.label :height_frame_depth, '縦：' %>
  <%= inner_sash.number_field :height_frame_depth, required: true, min: 1 %>
</div>
<div class="form-group">
  <%= inner_sash.label :width_frame_depth, '横：' %>
  <%= inner_sash.number_field :width_frame_depth, required: true, min: 1 %>
</div>

app/views/inner_sashes/_order_link.html.erb
<%= link_to "#{InnerSash.orders_i18n[order_key.to_sym]}にする",
    inner_sashes_update_order_path(id: inner_sash.id, order: order_key), class: "d-lg-none",
    data: {turbo_method: :post, turbo_confirm: "#{InnerSash.orders_i18n[order_key.to_sym]}にしますか？"} %>

<%= link_to "#{InnerSash.orders_i18n[order_key.to_sym]}にする",
    inner_sashes_update_order_path(id: inner_sash.id, order: order_key), class: "d-none d-lg-inline btn btn-#{order_key} py-1 px-3",
    data: {turbo_method: :post, turbo_confirm: "#{InnerSash.orders_i18n[order_key.to_sym]}にしますか？"} %>

app/views/inner_sashes/_shoji_and_glass.html.erb
<%= turbo_frame_tag 'shoji-and-glass' do %>
  <div class='row text-center'>
    <div class="col-12 row g-0 data-list align-items-center justify-content-center border-bottom">
      <span class="col-6 col-md-5 col-lg-4 fw-bold">中桟</span>
      <span class="col-6 col-md-5 col-lg-4"><%= inner_sash.middle_frame_height %></span>
    </div>
    <div class="col-12 row border-bottom g-0 data-list align-items-center justify-content-center">
      <span class="col-6 col-md-5 col-lg-4 fw-bold">クレセント</span>
      <span class="col-6 col-md-5 col-lg-4"><%= inner_sash.key_height %></span>
    </div>
    <p class='fw-bold mt-2 mb-2'>ガラス</p>
    <div class="col-12 row g-0 data-list-2">
      <div class="border-bottom row g-0 data-list d-flex align-items-center justify-content-center">
        <span class='col-6 col-md-5 col-lg-4 fw-bold'>種類</span>
        <span class="col-6 col-md-5 col-lg-4"><%= inner_sash.glass_kind_i18n %></span>
      </div>
      <div class="border-bottom row g-0 data-list d-flex align-items-center justify-content-center">
        <span class="col-6 col-md-5 col-lg-4 fw-bold">色</span>
        <span class="col-6 col-md-5 col-lg-4"><%= inner_sash.glass_color_i18n %></span>
      </div>
      <div class="border-bottom row g-0 data-list d-flex align-items-center justify-content-center">
        <span class="col-6 col-md-5 col-lg-4 fw-bold">単板・複層</span>
        <span class="col-6 col-md-5 col-lg-4"><%= inner_sash.glass_thickness_i18n %></span>
      </div>
      <div class="border-bottom row g-0 data-list d-flex align-items-center justify-content-center">
        <span class="col-6 col-md-5 col-lg-4 fw-bold">Low-E</span>
        <span class="col-6 col-md-5 col-lg-4"><%= inner_sash.is_low_e ? "有" : "無" %></span>
      </div>
      <div class="row g-0 mt-4 mt-md-5 align-items-center">
        <div class="col-3 mb-5">
          <% if @inner_sash.previous.present? %>
            <%= link_to inner_sashes_navigate_page_path(id: @inner_sash.previous, template: 'shoji_and_glass'), data: {turbo_method: :post} do %>
              <i class="bi bi-arrow-left-circle-fill h1"></i>
            <% end %>
          <% end %>
        </div>
        <div class="col-6 mb-5">
          <%= link_to '編集', inner_sashes_switch_path(template: 'edit_shoji_and_glass', id: inner_sash.id), data: {turbo_stream: true}, class: 'btn btn-primary bright-color col-11 col-lg-6' %>
        </div>
        <div class="col-3 mb-5">
          <% if @inner_sash.next.present? %>
            <%= link_to inner_sashes_navigate_page_path(id: @inner_sash.next, template: 'shoji_and_glass'), data: {turbo_method: :post}, class: 'd-block h-100' do %>
              <i class="bi bi-arrow-right-circle-fill h1"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/inner_sashes/_shoji_and_glass_info.html.erb
<%= turbo_frame_tag 'shoji-and-glass' do %>
  中桟<%= @inner_sash.middle_frame_height %>
  クレセント<%= @inner_sash.key_height %>

  <p>ガラス</p>
  種類<%= @inner_sash.glass_kind_i18n %>
  色<%= @inner_sash.glass_color_i18n %>
  単板・複層<%= @inner_sash.glass_thickness_i18n %>
  Low-E<%= @inner_sash.is_low_e ? "有" : "無" %>
<% end %>

app/views/inner_sashes/_site_label.html.erb
<div class="container-fluid site-label">
  <div class="row text-center">
    <p class='col my-1 fw-bold text-truncate'><span class='d-none d-lg-inline'>元請：</span><%= parent.contractor.name %></p>
    <p class='col my-1 fw-bold text-truncate'><span class='d-none d-lg-inline'>現場名：</span><%= parent.name %></p>
    <p class='col my-1 fw-bold text-truncate'><span class='d-none d-lg-inline'>住所：</span><%= parent.address %></p>
  </div>
</div>

app/views/inner_sashes/_tabs.html.erb
<ul class="nav nav-tabs nav-fill">
  <li class='nav-item'>
    <%= link_to inner_sashes_switch_path(template: 'basic_info', id: @inner_sash.id), class: "nav-link #{is_active(@template, 'basic_info')}",
        data: { turbo_stream: true } do %>
      <p class="d-md-none m-0">寸法</p>
      <p class="d-none d-md-block m-0">基本情報</p>
    <% end %>
  </li>
  <li class='nav-item'>
    <%= link_to inner_sashes_switch_path(template: 'shoji_and_glass', id: @inner_sash.id), class: "nav-link #{is_active(@template, 'shoji_and_glass')}",
        data: { turbo_stream: true } do %>
      <p class="d-md-none m-0">障子</p>
      <p class="d-none d-md-block m-0">障子・ガラス</p>
    <% end %>
  </li>
  <li class='nav-item'>
    <%= link_to inner_sashes_switch_path(template: 'photo_and_others', id: @inner_sash.id), class: "nav-link #{is_active(@template, 'photo_and_others')}",
        data: { turbo_stream: true} do %>
      <p class="d-md-none m-0">写真</p>
      <p class="d-none d-md-block m-0">写真・その他</p>
    <% end %>    
  </li>
</ul>

app/views/inner_sashes/edit.turbo_stream.erb
<%= turbo_stream.update 'room', class: 'col' do %>
  <%= form_with model: @inner_sash, url: inner_sashes_update_path(@inner_sash.id), class: 'row' do |f| %>
    <div class="col-8">
      <%= f.text_field :room, class: 'w-100'  %>
    </div>
    <div class="col-4">
      <%= f.submit "更新", class: 'btn btn-primary px-4 py-0' %>
    </div>
  <% end %>
<% end %>
<%= turbo_stream.update 'edit-btn' do %>
  <div>
    <%= link_to 'キャンセル', inner_sashes_switch_path(template: 'edit_cancel', id: @inner_sash.id), class: 'btn btn-secondary px-4 py-0' %>
  </div>
<% end %>

app/views/inner_sashes/edit_shoji_and_glass.turbo_stream.erb
<%= turbo_stream.update 'shoji-and-glass' do %>
  <%= form_with model: @inner_sash, url: inner_sashes_update_path(@inner_sash.id), class: 'row justify-content-center' do |inner_sash| %>
    <div class="col-12 col-md-10 col-lg-7">
      <%= render partial: 'shoji_and_glass_fields', locals: { inner_sash:  inner_sash } %>
    </div>
    <%= inner_sash.hidden_field :template, value: 'shoji_and_glass'  %>
    <div class="row justify-content-center p-3 mb-lg-2">
      <%= inner_sash.submit '保存', class: 'btn btn-primary col-9 col-md-4 col-lg-2' %>
    </div>
  <% end %>
  <div class="row justify-content-center p-3 mb-lg-5">
    <%= link_to 'キャンセル', inner_sashes_switch_path(template: 'shoji_and_glass',id: @inner_sash.id), data: {turbo_stream: true}, class: 'btn btn-secondary col-9 col-md-4 col-lg-2' %>
  </div>
<% end %>

app/views/inner_sashes/navigate_page.turbo_stream.erb
<%= turbo_stream.update'order-link' do %>
  <%= render partial: 'order_link', locals: {order_key: @order_key, inner_sash: @inner_sash} %>
<% end %>
<%= turbo_stream.update 'inner-sash-delete' do %>
  <%= link_to '削除', inner_sashes_destroy_path(id: @inner_sash.id), data: {turbo_method: :delete, turbo_confirm: "本当に削除しますか？" }, class: 'btn btn-danger px-4 py-0'%>
<% end %>
<%= turbo_stream.update 'inner-sash-data-wrap' do %>
  <%= turbo_frame_tag 'drawing' do %>
    <%= render 'drawing_tabs', inner_sash: @inner_sash %>
    <div class="row justify-content-center" style='height:350px;'>
      <%= render 'drawing', inner_sash: @inner_sash %>
    </div>
  <% end %>
  <div id="inner-sash-data" class='mb-3'>
    <%= render 'tabs' %>
    <%= render @template, inner_sash: @inner_sash %>
  </div>
<% end %>

app/views/inner_sashes/photo_and_others.turbo_stream.erb
<%= turbo_stream_flash %>
<%= turbo_stream.update 'inner-sash-data' do %>
  <%= render 'tabs' %>
  <%= render 'photo_and_others', inner_sash: @inner_sash %>
<% end %>

app/views/inner_sashes/room.turbo_stream.erb
<%= turbo_stream_flash %>
<%= turbo_stream.update 'room' do %>
  <p class='m-0'><%= @inner_sash.room %></p>
<% end %>
<%= turbo_stream.update 'edit-btn' do %>
  <div>
    <%= link_to '編集', inner_sashes_edit_room_path(@inner_sash.id), class: 'btn btn-primary px-4 py-0', data:{ turbo_stream: true} %>
  </div>
<% end %>

app/views/inner_sashes/show.html.erb
<%= render 'site_label', parent: @inner_sash.site_memo.site  %>
  <div class="container" style='margin-top:88px;'>
  <div class="row d-sm-none">
    <div class="col <%= @inner_sash.order %>-label p-1 mb-2">
      <%= turbo_frame_tag 'order' do %>
        <p class='bright-color m-0'><%= @inner_sash.order_i18n %></p>
      <% end %>
    </div>
  </div>
  <div class="row align-items-center text-center mb-3" style='height:60px;'>
    <%= turbo_frame_tag 'room', class: 'col' do %>
      <p class='m-0'><%= @inner_sash.room %></p>
    <% end %>
    <div class="col">
      <p class='m-0'>内窓</p>
    </div>
    <%= turbo_frame_tag 'edit-btn', class: 'col' do %>
      <div>
        <%= link_to '編集', inner_sashes_edit_room_path(@inner_sash.id), class: 'btn btn-primary px-4 py-0', data:{ turbo_stream: true} %>
      </div>
    <% end %>
    <div class="col-2 d-none d-sm-block">
      <%= turbo_frame_tag 'order-pc' do %>
        <div class="badge <%= @inner_sash.order %>-label py-1 px-3">
          <p class='bright-color m-0'><%= @inner_sash.order_i18n %></p>
        </div>
      <% end %>
    </div>
    <div class="col-1 p-0 dropdown d-lg-none">
      <a class="dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-three-dots-vertical h1"></i>
      </a>
      <ul class="dropdown-menu mt-2">
        <li>
          <%= turbo_frame_tag 'order-link', class: 'dropdown-item'  do %>
            <%= render partial: 'order_link', locals: {order_key: @order_key, inner_sash: @inner_sash} %>
          <% end %>
        </li>
        <li>
          <p class='dropdown-item m-0'>
            <%= link_to '削除', inner_sashes_destroy_path(id: @inner_sash.id), data: {turbo_method: :delete, turbo_confirm: "本当に削除しますか？" }%>
          </p>
        </li>
      </ul>
    </div>
    <div class="col d-none d-lg-block">
      <%= turbo_frame_tag 'order-link-pc' do %>
        <%= render partial: 'order_link', locals: {order_key: @order_key, inner_sash: @inner_sash} %>
      <% end %>
    </div>
    <div class="col d-none d-lg-block">
        <%= link_to '削除', inner_sashes_destroy_path(id: @inner_sash.id), data: {turbo_method: :delete, turbo_confirm: "本当に削除しますか？" }, class: 'btn btn-danger px-4 py-0'%>
    </div>
  </div>
  <%= turbo_frame_tag 'inner-sash-data-wrap' do %>
    <%= turbo_frame_tag 'drawing' do %>
      <%= render 'drawing_tabs', {inner_sash: @inner_sash, opening: 'active'} %>
      <div class="row justify-content-center" style='height:350px;'>
        <%= render 'drawing', inner_sash: @inner_sash %>
      </div>
    <% end %>
    <%= turbo_frame_tag 'inner-sash-data' do %>
      <%= render 'tabs' %>
      <%= render 'basic_info', inner_sash: @inner_sash %>
    <% end %>
  <% end %>
</div>

<%= stylesheet_link_tag "show", "data-turbo-track": "reload" %>

<% content_for :js do %>
  <%= javascript_import_module_tag "draw_opening" %>
<% end %>

app/views/inner_sashes/update_order.turbo_stream.erb
<%= turbo_stream_flash %>
<%= turbo_stream.update 'order-pc' do %>
  <div class="badge <%= @inner_sash.order %>-label py-1 px-3">
    <p class='bright-color m-0'><%= @inner_sash.order_i18n %></p>
  </div>
<% end %>
<%= turbo_stream.update "order-link-pc" do %>
  <%= render partial: 'order_link', locals: {order_key: @order_key, inner_sash: @inner_sash} %>
<% end %>
<%= turbo_stream.update 'order' do %>
  <p class='bright-color m-0'><%= @inner_sash.order_i18n %></p>
<% end %>
<%= turbo_stream.update "order-link" do %>
  <%= render partial: 'order_link', locals: {order_key: @order_key, inner_sash: @inner_sash} %>
<% end %>