config/routes.rb
Rails.application.routes.draw do
  get 'site_memos/index/:site_id', to: 'site_memos#index', as: :site_memos_index
  post 'site_memos/update_bulk_order/:site_id/:order', to: 'site_memos#update_bulk_order', as: :site_memos_update_bulk_order
  get 'site_memos/show_switcher/:kind/:child_id', to: 'site_memos#show_switcher', as: :site_memos_show_switcher
  get 'site_memos/new_step1/:site_id', to: 'site_memos#new_step1', as: :site_memos_new_step1
  post 'site_memos/form_switcher'
  delete 'site_memos/destroy/:kind/:child_id', to: 'site_memos#destroy', as: :site_memos_destroy
  get 'inner_sashes/new_step2'
  post 'inner_sashes/new_append_room'
  get 'inner_sashes/new_step3'
  patch 'inner_sashes/new_append_basic_info'
  get 'inner_sashes/new_step4'
  patch 'inner_sashes/new_append_shoji_and_glass'
  get 'inner_sashes/new_step5'
  patch 'inner_sashes/new_append_photo_and_others'
  get 'inner_sashes/new_comfirmation'
  get 'inner_sashes/show/:id', to: 'inner_sashes#show', as: :inner_sashes_show
  delete 'inner_sashes/destroy/:id', to: 'inner_sashes#destroy', as: :inner_sashes_destroy
  post 'inner_sashes/navigate_page/:id/:template', to:'inner_sashes#navigate_page', as: :inner_sashes_navigate_page
  get 'inner_sashes/edit_room/:id', to: 'inner_sashes#edit_room', as: :inner_sashes_edit_room
  post 'inner_sashes/update_order/:id/:order', to: 'inner_sashes#update_order', as: :inner_sashes_update_order
  get 'inner_sashes/switch/:template/:id', to: 'inner_sashes#switch', as: :inner_sashes_switch
  patch 'inner_sashes/update/:id', to: 'inner_sashes#update', as: :inner_sashes_update
  patch 'inner_sashes/glass_append'
  delete 'photos/destroy_existing_photo_form/:id', to: 'photos#destroy_existing_photo_form', as: :photos_destroy_existing_photo_form
  delete 'photos/destroy_new_photo_form/:index', to: 'photos#destroy_new_photo_form', as: :photos_destroy_new_photo_form
  root 'homes#top'
  get 'sign_in/index'
  get 'sign_up/index'
  get 'sign_up/step1'
  get 'sign_up/step2'
  get 'sign_up/done'
  get 'sign_up/resend_confirmation_code'
  post 'sign_up/create'
  get 'sites/index'
  get 'sites/new'
  delete 'sites/destroy/:id', to: 'sites#destroy', as: :sites_destroy
  get 'sites/search_contractor'
  post 'sites/create'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/site_memo.rb
class SiteMemo < ApplicationRecord
  enum kind: { inner_sash: 0 } 
  enum status: { step2: 0, step3: 1, step4: 2, step5: 3, comfirmation: 4 }

  belongs_to :site
  has_many :inner_sashes, dependent: :destroy
  accepts_nested_attributes_for :inner_sashes

  validates :kind, presence: true
  validates :status, presence: true
  validates :remark, length: { maximum:100 }

  def update_status(action:)
    status = action.sub('new_','')
    self.update(status: status)
  end
end

app/controllers/site_memos_controller.rb
class SiteMemosController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_site, only: [:new_step1]
  before_action :correct_child, only: [:show_switcher, :destroy]


  permits :kind

  def index(site_id:)
    #site_memosに新しい子モデルができたらそれに応じて取得するものを動的に変える    
    @site = current_user.sites.preload(site_memos: :inner_sashes).find(site_id)
    #あとでページネーションを考える
    @site_memos = @site.site_memos
    @order_key = get_opposite_order_key(site_memos: @site_memos)
  end

  def update_bulk_order(site_id:, order:)
    @site = current_user.sites.preload(site_memos: :inner_sashes).find(site_id)
    @site_memos = @site.site_memos
    update_childs_order(site_memos: @site_memos, order: order)
    # あとでページネーション考える
    @order_key = get_opposite_order_key(site_memos: @site_memos)
    flash.now.notice = "全て#{ InnerSash.orders_i18n[order.to_sym]}にしました"
  end

  def new_step1(site_id:)
    session[:site_id] = site_id
    @site_memo = SiteMemo.new
  end

  def form_switcher(site_memo)
    kind = site_memo[:kind]
    site_id = session[:site_id]

    # 新規作成用
    @site_memo = SiteMemo.new(site_id: site_id, kind: kind)
    # 既存を取得
    ex_sash_memo = SiteMemo.find_by(site_id: site_id, kind: kind)

    if ex_sash_memo.blank? && @site_memo.save
      return redirect_to "/#{kind.pluralize}/new_step2"
    elsif ex_sash_memo.blank?
      return render 'new_step1', status: :unprocessable_entity
    end

    # 既存のデータがあるならダイレクト先でデータを更新していく
    kind = ex_sash_memo.kind.to_s.pluralize
    status = ex_sash_memo.status

    return redirect_to "/#{kind}/new_#{status}" if ex_sash_memo && status !='comfirmation'
    return redirect_to "/#{kind}/new_step2"
  end

  def show_switcher(kind:, child_id:)
    redirect_to inner_sashes_show_path(id: child_id) if kind == 'inner_sash' 
    #他のモデルが追加されたら分岐を追加
  end

  def destroy(kind:, child_id:)
    #site_memo/indexに表示されているinner_sashを削除。その後turbo_stream
    #他のモデルが追加されたら分岐を追加
    @inner_sash&.destroy_last_with(site_memo: @inner_sash.site_memo)
    flash.now.notice = 'メモを削除しました'
  end

  private

  def update_childs_order(site_memos:, order:)
    #site_memosモデルに子モデルができたら条件追加。コメントアウトも外す
    site_memos.each do |site_memo|
      site_memo.inner_sashes.update_all(order: order) if site_memo.kind == 'inner_sash'
    end
  end

  def correct_child(kind:, child_id:)
    #子モデルが追加され次第分岐する
    inner_sash = InnerSash.find(child_id) # if kind == 'inner_sash'
    redirect_to root_path if inner_sash.site_memo.site.user_id != current_user.id
  end

  def correct_site(site_id:)
    @site = Site.find(site_id)
    redirect_to root_path if @site.user_id != current_user.id
  end
end

app/helpers/site_memos_helper.rb
module SiteMemosHelper
  def site_memo_children(site_memo)
    return site_memo.inner_sashes if site_memo.kind == 'inner_sash'
  end
end

app/views/site_memos/_bulk_order_link.html.erb
<%= link_to site_memos_update_bulk_order_path(site_id: @site.id, order: @order_key),
  class: 'btn btn-primary px-2 py-3 d-flex col-9 col-sm-7 col-md-4 col-lg-3 h-75',
  data: {turbo: true, turbo_method: :post, turbo_confirm: "全て#{InnerSash.orders_i18n[@order_key.to_sym]}にしますか？(表示されていないものも含みます)"} do %>
  <span class='col align-self-center'><%= "一括#{InnerSash.orders_i18n[@order_key.to_sym]}" %></span>
<% end %> 

app/views/site_memos/_inner_sash_fields.html.erb
<tr class="nested-fields">
  <td>
    <div class="form-group">
      <%= f.text_field :room %>
    </div>
  </td>
  <td>
    <div class="form-group">
      <%= f.label :width_up_size, '上:' %>
      <%= f.number_field :width_up_size %>
    </div>
    <div class="form-group">
      <%= f.label :width_middle_size, '中:' %>
      <%= f.number_field :width_middle_size %>
    </div>
    <div class="form-group">
      <%= f.label :width_down_size, '下:' %>
      <%= f.number_field :width_down_size %>
    </div>
  </td>
  <td>
    <div class="form-group">
      <%= f.label :height_left_size, '左:' %>
      <%= f.number_field :height_left_size %>
    </div>
    <div class="form-group">
      <%= f.label :height_middle_size, '中:' %>
      <%= f.number_field :height_middle_size %>
    </div>
    <div class="form-group">
      <%= f.label :height_right_size, '右:' %>
      <%= f.number_field :height_right_size %>
    </div>
  </td>
  <td>
    <div class="form-group">
      <%= f.label :height_frame_depth, '縦:' %>
      <%= f.number_field :height_frame_depth %>
    </div>
    <div class="form-group">
      <%= f.label :width_frame_depth, '横:' %>
      <%= f.number_field :width_frame_depth %>
    </div>
  </td>
  <td>
    <%= link_to_remove_association "削除", f %>
  </td>
</tr>

app/views/site_memos/_site_memo.html.erb
<% site_memo.inner_sashes.each do |inner_sash| %>
  <% order = inner_sash.order_i18n %>
  <%= turbo_frame_tag dom_id(inner_sash), class:'col-12 col-md-6 col-lg-4' do %>
    <div class='card card-custom mb-4'>
      <div class="card-body">
        <div class="row mb-1">
          <h5 class="col-7 card-title text-truncate"><%= inner_sash.room %></h5>
          <div class="col-4">
            <% if order == '未発注' %>
              <span class="badge bg-danger ps-3 pe-3"><%= order %></span>
            <% else %>
              <span class="badge bg-primary ps-3 pe-3"><%= order %></span>
            <% end %>
          </div>
          <a class="text-center p-0 col-1 dorpdown-toggle dropdown-toggle-custom" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="mx-auto bi bi-three-dots-vertical h5"></i>
          </a>
          <ul class='col-5 dropdown-menu text-center'>
            <li><%= link_to '削除', site_memos_destroy_path(kind: site_memo.kind, child_id: inner_sash.id),class: 'dropdown-item danger-color p-0' ,data: { turbo_method: :delete, turbo_confirm: "本当に削除しますか？" } %></li>
          </ul>
        </div>
        <div class='row justify-content-center position-relative mt-3'>
          <div class='col-11 row border-index p-1 mb-3'>
            <span class='col-4'>施工内容</span>
            <span class='col-7'><%= site_memo.kind_i18n %></span>
          </div>
          <div class='col-11 row border-index p-1 mb-3'>
            <span class='col-4'>タイプ</span>
            <span class='col-7'><%= inner_sash.sash_type_i18n %></span>
          </div>
          <%# リンク広がっている %>
          <%= link_to '', site_memos_show_switcher_path(kind: site_memo.kind, child_id: inner_sash.id), data: { turbo: false }, class: 'to-memo-link' %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/site_memos/destroy.turbo_stream.erb
<%= turbo_stream_flash %>
<%= turbo_stream.remove @inner_sash %>

app/views/site_memos/index.html.erb
<%= render 'inner_sashes/site_label', parent: @site  %>

<div class="container index-wrap">
  <div class='index'>
    <% if @site_memos.blank? %>
      <div class="text-center mt-5">
        <p>メモはありません</p>
      </div>
    <% else %>
      <%= turbo_frame_tag 'site-memos-list', class: 'row justify-content-center' do %>
        <div class="d-flex justify-content-center bulk-btn mb-3">
          <%= render 'bulk_order_link' %>
        </div>
        <%= render @site_memos %>
      <% end %>
    <% end %>
  </div>
  <div class="row justify-content-end p-3 mb-lg-5 z-3">
    <%= link_to site_memos_new_step1_path(@site.id), class: 'btn-circle submit-btn col-3 col-md-4 col-lg-2 p-0 text-center' do %>
      <i class="bi bi-plus plus"></i>
    <% end %>
  </div>
</div>

<%= stylesheet_link_tag "index", "data-turbo-track": "reload" %>

app/views/site_memos/new_step1.html.erb
<%= render 'inner_sashes/site_label', parent: @site %>
<div class="container" style="margin-top: 15vh;">
  <%= form_with model: @site_memo, url: site_memos_form_switcher_path, local: true, class: 'row justify-content-center' do |f| %>
    <%= render 'layouts/alert', obj: f.object %>
    <div class="col-11 col-md-8 col-lg-5 mb-3 mb-md-4">
      <%= f.label :kind, '施工内容', class: 'form-label' %><span class="badge bg-danger ms-2">必須</span><br />
      <%= f.select :kind, SiteMemo.kinds.keys.map{ |k| [I18n.t("enums.site_memo.kind.#{k}"),k]}, {prompt: '選択してください'}, class: 'form-select' %>
    </div>
    <div class="row justify-content-center p-3 submit-btn mb-lg-5">
      <%= f.submit '次へ', class: 'btn btn-primary col-9 col-md-4 col-lg-2' %>
    </div>
  <% end %>
</div>

app/views/site_memos/new_step2_inner_sash.html.erb
<p>内窓用フォーム</p>

<%= form_with model: @site_memo, url: site_memos_new_step3_inner_sash_path, method: :get, local: true do |f| %>
  <table>
    <tr>
      <th>部屋</th>
      <th>W寸法</th>
      <th>H寸法</th>
      <th>窓枠見込み</th>
    </tr>
    <%= f.fields_for :inner_sashs do |t| %>
      <%= render 'inner_sash_fields', f: t %>
    <% end %>
    <tr id="detail-association-insertion-point"></div> 
  </table>
  <%= link_to_add_association '場所追加', f, :inner_sashs,
  data: {
    association_insertion_node: '#detail-association-insertion-point',
    association_insertion_method: 'before'
  }%>
  <div class="form_group">
    <%= f.submit '次へ' %>
  </div>
<% end %>

app/views/site_memos/new_step3_inner_sash.html.erb
<p>ステップ３</p>
<%= form_with url: site_memos_new_step4_inner_sash_path, method: :get, local: true do |f| %>
  <table>
    <tr>
      <th>部屋</th>
      <th>タイプ</th>
      <th>色</th>
      <th>障子枚数</th>
      <th>吊元（開きのみ）</th>
    </tr>
    <tr>
      <td>
        
      </td>
      <td>
        <%= f.select :type, ['引き違い', '開き'], {prompt: '選択してください'} %>
      </td>
      <td><%= f.select :color, ['色１', '色2'], {prompt: '選択してください'} %></td><!-- enum使う -->
      <td><%= f.select :number_of_shoji, [1, 2, 3, 4], {prompt: '選択してください'} %></td>
      <td>開きを選択したときにチェックボックス</td>
    </tr>
  </table>
<% end %>

app/views/site_memos/update_bulk_mobile_order.turbo_stream.erb
<!-- モバイル用 -->
<%= turbo_stream_flash %>
<%= turbo_stream.update "site-memos-list" do %>
  <div class="submit-btn d-flex justify-content-start justify-content-md-center">
    <%= render 'bulk_order_link', devise: 'mobile' %>
  </div>
  <%= render @site_memos %>
<% end %>

app/views/site_memos/update_bulk_order.turbo_stream.erb
<%= turbo_stream_flash %>
<%= turbo_stream.update "site-memos-list" do %>
  <div class="d-flex justify-content-center bulk-btn mb-3">
    <%= render 'bulk_order_link' %>
  </div>
  <%= render @site_memos %>
<% end %>